---
- name: Register VM_IP Artifact
  hosts: localhost
  gather_facts: False
  connection: local
  
  tasks:
  - name: Save host data within a Group
    add_host:
      hostname: "{{ vm_ip }}"
      groupname: hardening_servers

  - name: Wait for SSH to come up
    wait_for: host={{ vm_ip }} port=22 delay=10 timeout=60
    
- name: install and configure AIDE as IDS
  hosts: hardening_servers
  become: true
  tasks:
  - name: Ensure AIDE is installed
    package:
      name: '{{ item }}'
      state: present
    with_items:
      - aide
    when: ansible_virtualization_type not in ["docker", "lxc", "openvz"]
    tags:
      - aide_periodic_cron_checking
      - medium_severity
      - restrict_strategy
      - low_complexity
      - low_disruption
      - no_reboot_needed
      - CCE-80676-0
      - NIST-800-53-SI-7
      - NIST-800-53-SI-7(1)
      - NIST-800-53-CM-6(a)
      - PCI-DSS-Req-11.5
      - CJIS-5.10.1.3

  - name: Configure Periodic Execution of AIDE
    cron:
      name: run AIDE check
      minute: '5'
      hour: '4'
      weekday: '0'
      user: root
      job: /usr/sbin/aide --check
    when: ansible_virtualization_type not in ["docker", "lxc", "openvz"]
    tags:
      - aide_periodic_cron_checking
      - medium_severity
      - restrict_strategy
      - low_complexity
      - low_disruption
      - no_reboot_needed
      - CCE-80676-0
      - NIST-800-53-SI-7
      - NIST-800-53-SI-7(1)
      - NIST-800-53-CM-6(a)
      - PCI-DSS-Req-11.5
      - CJIS-5.10.1.3

  - name: Build and Test AIDE Database
    command: /usr/sbin/aide --init
    changed_when: true
    when: ansible_virtualization_type not in ["docker", "lxc", "openvz"]
    tags:
      - aide_build_database
      - medium_severity
      - restrict_strategy
      - low_complexity
      - low_disruption
      - no_reboot_needed
      - CCE-80675-2
      - NIST-800-53-CM-6(a)
      - PCI-DSS-Req-11.5
      - CJIS-5.10.1.3

  - name: Check whether the stock AIDE Database exists
    stat:
      path: /var/lib/aide/aide.db.new.gz
    register: aide_database_stat
    when: ansible_virtualization_type not in ["docker", "lxc", "openvz"]
    tags:
      - aide_build_database
      - medium_severity
      - restrict_strategy
      - low_complexity
      - low_disruption
      - no_reboot_needed
      - CCE-80675-2
      - NIST-800-53-CM-6(a)
      - PCI-DSS-Req-11.5
      - CJIS-5.10.1.3

  - name: Stage AIDE Database
    copy:
      src: /var/lib/aide/aide.db.new.gz
      dest: /var/lib/aide/aide.db.gz
      backup: true
      remote_src: true
    when:
      - (aide_database_stat.stat.exists is defined and aide_database_stat.stat.exists)
      - ansible_virtualization_type not in ["docker", "lxc", "openvz"]
    tags:
      - aide_build_database
      - medium_severity
      - restrict_strategy
      - low_complexity
      - low_disruption
      - no_reboot_needed
      - CCE-80675-2
      - NIST-800-53-CM-6(a)
      - PCI-DSS-Req-11.5
      - CJIS-5.10.1.3
