---
- name: Register VM_IP Artifact
  hosts: localhost
  gather_facts: False
  connection: local
  
  tasks:
  - name: Save host data within a Group
    add_host:
      hostname: "{{ vm_ip }}"
      groupname: hardening_servers

  - name: Wait for SSH to come up
    wait_for: host={{ vm_ip }} port=22 delay=10 timeout=60
    
- name: Hardening Passwords
  hosts: hardening_servers
  become: true
  tasks:
  - name: Set Password Maximum Age
    lineinfile:
      create: true
      dest: /etc/login.defs
      regexp: ^#?PASS_MAX_DAYS
      line: PASS_MAX_DAYS {{ var_accounts_maximum_age_login_defs }}

  - name: Set Existing Passwords Maximum Age - Collect Users With Incorrect Number of Days of Maximum Before Password Expires
    ansible.builtin.command:
      cmd: awk -F':' '(($5 > {{ var_accounts_maximum_age_login_defs }} || $5 == "") && $2 ~ /^\$/) {print $1}' /etc/shadow
    register: result_pass_max_age_user_names
    changed_when: false

  - name: Set Existing Passwords Maximum Age - Ensure the Number of Days of Maximum Before Password Expires
    ansible.builtin.command:
      cmd: chage -M {{ var_accounts_maximum_age_login_defs }} {{ item }}
    with_items: '{{ result_pass_max_age_user_names.stdout_lines }}'
    when:
    - result_pass_max_age_user_names is not skipped and result_pass_max_age_user_names.stdout_lines | length > 0

  - name: Set Existing Passwords Warning Age - Collect Users With Incorrect Number of Days of Warning Before Password Expires
    ansible.builtin.command:
      cmd: awk -F':' '(($6 < {{ var_accounts_password_warn_age_login_defs }} || $6 == "") && $2 ~ /^\$/) {print $1}' /etc/shadow
    register: result_pass_warn_age_user_names
    changed_when: false
  
  - name: Set Existing Passwords Warning Age - Ensure the Number of Days of Warning Before Password Expires
    ansible.builtin.command:
      cmd: chage --warndays {{ var_accounts_password_warn_age_login_defs }} {{ item }}
    with_items: '{{ result_pass_warn_age_user_names.stdout_lines }}'
    when:
    - result_pass_warn_age_user_names is not skipped and result_pass_warn_age_user_names.stdout_lines | length > 0
  
  - name: Set Interactive Session Timeout
    lineinfile:
      path: /etc/profile.d/tmout.sh
      create: true
      regexp: TMOUT=
      line: typeset -xr TMOUT={{ var_accounts_tmout }}
      state: present
    when:
    - ansible_virtualization_type not in ["docker", "lxc", "openvz", "podman", "container"]
  
  - name: Ensure PAM Enforces Password Requirements - Minimum Digit Characters - Ensure PAM variable dcredit is set accordingly
    ansible.builtin.lineinfile:
      create: true
      dest: /etc/security/pwquality.conf
      regexp: ^#?\s*dcredit
      line: dcredit = {{ var_password_pam_dcredit }}
  
  - name: Ensure PAM Enforces Password Requirements - Minimum Lowercase Characters - Ensure PAM variable lcredit is set accordingly
    ansible.builtin.lineinfile:
      create: true
      dest: /etc/security/pwquality.conf
      regexp: ^#?\s*lcredit
      line: lcredit = {{ var_password_pam_lcredit }}
  
  - name: Ensure PAM Enforces Password Requirements - Minimum Length - Ensure PAM variable minlen is set accordingly
    ansible.builtin.lineinfile:
      create: true
      dest: /etc/security/pwquality.conf
      regexp: ^#?\s*minlen
      line: minlen = {{ var_password_pam_minlen }}

  - name: Update password for root 
    user: 
      name: root 
      password: "{{ ansible_password }}"
      update_password: always


  

